version: '3.8'

volumes:
  postgres_data:
  build_volume:
  static_volume:

networks:
  reverse_proxy:
    external: true

services:
  db:
    image: postgres:14.4-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - reverse_proxy

  backend:
    build:
      context: ./backend
      target: prod
    volumes:
      - ./backend/media:/backend/media
      - static_volume:/backend/django_static
    env_file:
      - ./.env
    depends_on:
      - db
    entrypoint: /backend/entrypoint.prod.sh
    networks:
      - reverse_proxy

  mailing:
    build:
      context: ./mailing
      target: prod
    env_file:
      - ./.env
    entrypoint: /mailing/entrypoint.prod.sh
    networks:
      - reverse_proxy

  frontend:
    build:
      context: ./frontend
      target: prod
    volumes:
      - build_volume:/frontend/build
    env_file:
      - ./.env
    entrypoint: /frontend/entrypoint.prod.sh

  nginx:
    image: nginx:1.23-alpine
    volumes:
      - build_volume:/var/www/html
      - static_volume:/backend/django_static
      - ./backend/media:/backend/media
      - ./nginx:/etc/nginx/conf.d
    expose:
      - 80
    depends_on:
      - backend
      - frontend
    environment:
      - VIRTUAL_HOST=clubs.iiit.ac.in
      - LETSENCRYPT_HOST=clubs.iiit.ac.in
    networks:
      - default
      - reverse_proxy
