version: '3'

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env

  backend:
    build: ./backend
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    volumes:
      - media_volume:/backend/media
      - static_volume:/backend/django_static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: yarn build
    volumes:
      - build_folder:/frontend/build
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./server/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
      - media_volume:/backend/media
      - static_volume:/backend/django_static
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  build_folder:
  media_volume:
  static_volume:
