version: '3'

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn backend.wsgi --bind 0.0.0.0:8000"
    volumes:
      - media_volume:/backend/media
      - static_volume:/backend/django_static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: >
      sh -c "cd live && 
             yarn && 
             yarn start"
    network_mode: host
    volumes:
      - ./frontend:/frontend/live
    ports:
      - 3000:3000
    env_file:
      - ./.env

volumes:
  postgres_data:
  media_volume:
  static_volume:
