version: '3'
services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env

  backend:
    build: ./backend
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    volumes:
      - media_volume:/backend/media
      - static_volume:/backend/django_static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - html_volume:/frontend/build
    env_file:
      - ./.env

  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - html_volume:/var/www/html
      - media_volume:/backend/media
      - static_volume:/backend/django_static
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  html_volume:
  media_volume:
  static_volume:
