version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:14.4-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env

  backend:
    user: $UID:$GID
    build:
      context: ./backend
      target: base
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    entrypoint: /backend/entrypoint.sh

  frontend:
    user: $UID:$GID
    build:
      context: ./frontend
      target: base
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    env_file:
      - ./.env
    entrypoint: /frontend/entrypoint.sh
    network_mode: host
